import type { ProjectAssetBundle } from "@/projects/assets/types";

function id(prefix: string, n: number): string {
  return `${prefix}_${n}`;
}

/** 确定性示例数据，便于 UI 演示 */
export function buildMockAssetBundle(projectId: string): ProjectAssetBundle {
  return {
    projectId,
    characters: [
      {
        id: id("char", 1),
        projectId,
        name: "林清",
        role: "女主角",
        description: "沉稳果敢，在危机中仍保持温柔与理性。",
        appearance: "长发及腰，眉眼清冷，气质干净。",
        clothing: "浅色长裙，偶着旅人披风。",
        age: "24",
        gender: "女",
        voiceId: null,
        voiceName: null,
        voiceStyle: null,
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "completed",
      },
      {
        id: id("char", 2),
        projectId,
        name: "顾衡",
        role: "男主角",
        description: "冷面热心，擅长谋略。",
        appearance: "短发利落，轮廓分明。",
        clothing: "深色劲装。",
        age: "27",
        gender: "男",
        voiceId: null,
        voiceName: null,
        voiceStyle: null,
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "completed",
      },
      {
        id: id("char", 3),
        projectId,
        name: "阿砚",
        role: "配角",
        description: "机灵的书童，消息灵通。",
        appearance: "少年模样，眼神活泼。",
        clothing: "素色短袍。",
        age: "16",
        gender: "男",
        voiceId: null,
        voiceName: null,
        voiceStyle: null,
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "pending",
      },
    ],
    scenes: [
      {
        id: id("scene", 1),
        projectId,
        name: "皇宫大厅",
        sceneType: "古代宫殿",
        description: "金碧辉煌的议事大厅，烛火摇曳。",
        timeOfDay: "夜晚",
        location: "皇城内廷",
        style: "金碧辉煌",
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "completed",
      },
      {
        id: id("scene", 2),
        projectId,
        name: "雨巷茶铺",
        sceneType: "市井",
        description: "",
        timeOfDay: "黄昏",
        location: "城东巷口",
        style: "",
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "draft",
      },
    ],
    props: [
      {
        id: id("prop", 1),
        projectId,
        name: "长剑",
        propType: "武器",
        usage: "角色战斗",
        description: "青铜剑身，剑穗素白。",
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "completed",
      },
      {
        id: id("prop", 2),
        projectId,
        name: "玉佩",
        propType: "信物",
        usage: "剧情线索",
        description: "半透明青玉，刻有云纹。",
        imageFileName: null,
        imageObjectUrl: null,
        imageMimeType: null,
        status: "completed",
      },
    ],
    audios: [
      {
        id: id("audio", 1),
        projectId,
        name: "宫廷氛围",
        type: "music",
        duration: "02:40",
        source: "本地上传（示例）",
        fileName: null,
        objectUrl: null,
        mimeType: null,
        status: "completed",
      },
      {
        id: id("audio", 2),
        projectId,
        name: "雨声循环",
        type: "sfx",
        duration: "00:45",
        source: "素材库（示例）",
        fileName: null,
        objectUrl: null,
        mimeType: null,
        status: "completed",
      },
      {
        id: id("audio", 3),
        projectId,
        name: "开场旁白",
        type: "narration",
        duration: "00:18",
        source: "待录制",
        fileName: null,
        objectUrl: null,
        mimeType: null,
        status: "draft",
      },
      {
        id: id("audio", 4),
        projectId,
        name: "清冷女声样例",
        type: "voice",
        duration: "",
        source: "示例条目（请上传真实文件后试听）",
        fileName: null,
        objectUrl: null,
        mimeType: null,
        status: "draft",
      },
    ],
  };
}
