import type { VoiceOption } from "@/projects/assets/types";

/**
 * Mock system voice catalog — structure matches future GET /api/voices/catalog.
 * previewUrl uses reserved API path; returns 501 until backend is wired.
 */
export const SYSTEM_VOICE_CATALOG: VoiceOption[] = [
  {
    id: "sys_voice_gentle_female",
    name: "温柔女声",
    label: "温柔女声",
    style: "温柔 · 叙事",
    gender: "female",
    ageRange: "青年",
    language: "中文",
    emotion: "温柔",
    tone: "中音",
    source: "system",
    description: "柔和清晰，适合情感对白与内心独白。",
    previewUrl: "/api/voices/sys_voice_gentle_female/preview",
    status: "ready",
  },
  {
    id: "sys_voice_mature_male",
    name: "成熟男声",
    label: "成熟男声",
    style: "沉稳 · 叙事",
    gender: "male",
    ageRange: "中年",
    language: "中文",
    emotion: "平静",
    tone: "低音",
    source: "system",
    description: "低沉稳重，适合旁白式对白与权威角色。",
    previewUrl: "/api/voices/sys_voice_mature_male/preview",
    status: "ready",
  },
  {
    id: "sys_voice_youth_female",
    name: "活泼少女",
    label: "活泼少女",
    style: "明亮 · 日常",
    gender: "female",
    ageRange: "少年",
    language: "中文",
    emotion: "活泼",
    tone: "高音",
    source: "system",
    description: "轻快明亮，适合青春题材与日常对话。",
    previewUrl: "/api/voices/sys_voice_youth_female/preview",
    status: "ready",
  },
  {
    id: "sys_voice_calm_neutral",
    name: "中性旁白",
    label: "中性旁白",
    style: "清晰 · 旁白",
    gender: "neutral",
    ageRange: "青年",
    language: "中文",
    emotion: "平静",
    tone: "中音",
    source: "system",
    description: "中性清晰，适合说明性旁白与过渡段落。",
    previewUrl: "/api/voices/sys_voice_calm_neutral/preview",
    status: "ready",
  },
  {
    id: "sys_voice_dramatic_male",
    name: "戏剧男声",
    label: "戏剧男声",
    style: "张力 · 冲突",
    gender: "male",
    ageRange: "青年",
    language: "中文",
    emotion: "激烈",
    tone: "中低音",
    source: "system",
    description: "富有张力，适合冲突场景与情绪爆发。",
    previewUrl: "/api/voices/sys_voice_dramatic_male/preview",
    status: "ready",
  },
  {
    id: "sys_voice_warm_aunt",
    name: "温暖阿姨",
    label: "温暖阿姨",
    style: "亲切 · 家庭",
    gender: "female",
    ageRange: "中年",
    language: "中文",
    emotion: "温暖",
    tone: "中音",
    source: "system",
    description: "亲切自然，适合家庭剧与长辈角色。",
    previewUrl: "/api/voices/sys_voice_warm_aunt/preview",
    status: "ready",
  },
  {
    id: "sys_voice_en_cool_female",
    name: "Cool English",
    label: "Cool English",
    style: "Cool · Narration",
    gender: "female",
    ageRange: "青年",
    language: "English",
    emotion: "平静",
    tone: "中音",
    source: "system",
    description: "Clear English voice for bilingual or overseas drama.",
    previewUrl: "/api/voices/sys_voice_en_cool_female/preview",
    status: "ready",
  },
  {
    id: "sys_voice_elder_male",
    name: "慈祥老者",
    label: "慈祥老者",
    style: "厚重 · 回忆",
    gender: "male",
    ageRange: "老年",
    language: "中文",
    emotion: "温和",
    tone: "低音",
    source: "system",
    description: "缓慢厚重，适合回忆、讲述与长者角色。",
    previewUrl: "/api/voices/sys_voice_elder_male/preview",
    status: "ready",
  },
];

export function findSystemVoice(voiceId: string): VoiceOption | null {
  return SYSTEM_VOICE_CATALOG.find((v) => v.id === voiceId) ?? null;
}

export function isSystemVoiceId(voiceId: string | null | undefined): boolean {
  return typeof voiceId === "string" && voiceId.startsWith("sys_voice_");
}
