import { mkdtempSync, readdirSync, rmSync } from "fs";
import os from "os";
import path from "path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const putRemoteAssetImage = vi.hoisted(() => vi.fn());
const deleteRemoteAssetImage = vi.hoisted(() => vi.fn());

vi.mock("@/persistence/remote-data-client", () => ({
  isRemoteDataOnly: () => true,
}));
vi.mock("@/projects/assets/remote-asset-blob-store", () => ({
  imageStorageKey: (projectId: string, assetId: string) =>
    `projects/${projectId}/asset-images/${assetId}`,
  putRemoteAssetImage,
  deleteRemoteAssetImage,
}));

import {
  deleteProjectAssetImageFile,
  writeProjectAssetImageFile,
} from "@/projects/assets/asset-image-storage";

describe("remote design asset image storage", () => {
  let isolatedRoot = "";

  beforeEach(() => {
    isolatedRoot = mkdtempSync(path.join(os.tmpdir(), "ic-remote-design-image-"));
    process.env.APP_DATA_DIR = path.join(isolatedRoot, "app-data");
    process.env.DATA_ROOT = path.join(isolatedRoot, "data-root");
    process.env.REMOTE_DATA_ONLY = "true";
    putRemoteAssetImage.mockReset();
    putRemoteAssetImage.mockResolvedValue(undefined);
    deleteRemoteAssetImage.mockReset();
    deleteRemoteAssetImage.mockResolvedValue(undefined);
  });

  afterEach(() => {
    delete process.env.APP_DATA_DIR;
    delete process.env.DATA_ROOT;
    delete process.env.REMOTE_DATA_ONLY;
    rmSync(isolatedRoot, { recursive: true, force: true });
  });

  it("writes generated bytes to the Go Blob service without local files", async () => {
    const buffer = Buffer.from([1, 2, 3]);
    const result = await writeProjectAssetImageFile({
      projectId: "project_1",
      assetId: "media_1",
      buffer,
      mimeType: "image/png",
    });

    expect(putRemoteAssetImage).toHaveBeenCalledWith({
      projectId: "project_1",
      assetId: "media_1",
      mimeType: "image/png",
      body: buffer,
    });
    expect(result).toEqual({
      mimeType: "image/png",
      sizeBytes: 3,
      filePath: "projects/project_1/asset-images/media_1",
    });
    expect(readdirSync(isolatedRoot)).toEqual([]);
  });

  it("deletes generated media through the Go Blob service", async () => {
    await deleteProjectAssetImageFile("project_1", "media_1");

    expect(deleteRemoteAssetImage).toHaveBeenCalledWith(
      "project_1",
      "media_1",
    );
    expect(readdirSync(isolatedRoot)).toEqual([]);
  });
});
